all: remove_dups k_to_last remove_middle

remove_dups: remove_dups.cpp
	g++ -o remove_dups remove_dups.cpp

k_to_last: k_to_last.cpp single_list.h
	g++ -o k_to_last k_to_last.cpp

remove_middle: remove_middle.cpp single_list.h
	g++ -o remove_middle remove_middle.cpp